import { FilterGroup, FilterKey, FilterKind, FilterState } from "./types";

export interface FilterMeta {
  key: FilterKey;
  label: string;
  group: FilterGroup;
  kind: FilterKind;
  min: number;
  max: number;
  step: number;
  unit?: string;
  description: string;
  defaultValue: number;
  defaultMin: number;
  defaultMax: number;
}

export const FILTER_GROUP_LABELS: Record<FilterGroup, string> = {
  geometric: "Geometric",
  color: "Color & Tone",
  texture: "Texture & Noise",
  creative: "Coin & Creative",
};

export const FILTER_REGISTRY: FilterMeta[] = [
  {
    key: "rotate",
    label: "Rotate",
    group: "geometric",
    kind: "range",
    min: -180,
    max: 180,
    step: 1,
    unit: "°",
    description: "Rotates the image around its center.",
    defaultValue: 15,
    defaultMin: -25,
    defaultMax: 25,
  },
  {
    key: "flipH",
    label: "Flip horizontal",
    group: "geometric",
    kind: "boolean",
    min: 0,
    max: 1,
    step: 1,
    description: "Mirrors the image left-to-right.",
    defaultValue: 0,
    defaultMin: 0,
    defaultMax: 0,
  },
  {
    key: "flipV",
    label: "Flip vertical",
    group: "geometric",
    kind: "boolean",
    min: 0,
    max: 1,
    step: 1,
    description: "Mirrors the image top-to-bottom.",
    defaultValue: 0,
    defaultMin: 0,
    defaultMax: 0,
  },
  {
    key: "zoom",
    label: "Zoom / crop-in",
    group: "geometric",
    kind: "range",
    min: 0,
    max: 40,
    step: 1,
    unit: "%",
    description: "Crops into the center then rescales back, simulating distance changes.",
    defaultValue: 10,
    defaultMin: 0,
    defaultMax: 20,
  },
  {
    key: "shear",
    label: "Shear (perspective)",
    group: "geometric",
    kind: "range",
    min: -20,
    max: 20,
    step: 1,
    unit: "°",
    description: "Slants the image, simulating a change in camera angle.",
    defaultValue: 0,
    defaultMin: -8,
    defaultMax: 8,
  },
  {
    key: "brightness",
    label: "Brightness",
    group: "color",
    kind: "range",
    min: 0.4,
    max: 2,
    step: 0.05,
    unit: "×",
    description: "Multiplies pixel brightness.",
    defaultValue: 1,
    defaultMin: 0.8,
    defaultMax: 1.3,
  },
  {
    key: "contrast",
    label: "Contrast",
    group: "color",
    kind: "range",
    min: 0.4,
    max: 2,
    step: 0.05,
    unit: "×",
    description: "Stretches or compresses tonal range.",
    defaultValue: 1,
    defaultMin: 0.8,
    defaultMax: 1.3,
  },
  {
    key: "saturation",
    label: "Saturation",
    group: "color",
    kind: "range",
    min: 0,
    max: 2,
    step: 0.05,
    unit: "×",
    description: "Adjusts color intensity.",
    defaultValue: 1,
    defaultMin: 0.7,
    defaultMax: 1.3,
  },
  {
    key: "hue",
    label: "Hue rotate",
    group: "color",
    kind: "range",
    min: 0,
    max: 359,
    step: 1,
    unit: "°",
    description: "Rotates all colors around the color wheel.",
    defaultValue: 0,
    defaultMin: 0,
    defaultMax: 15,
  },
  {
    key: "grayscale",
    label: "Grayscale",
    group: "color",
    kind: "boolean",
    min: 0,
    max: 1,
    step: 1,
    description: "Removes all color.",
    defaultValue: 0,
    defaultMin: 0,
    defaultMax: 0,
  },
  {
    key: "sepia",
    label: "Sepia tint",
    group: "color",
    kind: "boolean",
    min: 0,
    max: 1,
    step: 1,
    description: "Applies a warm brown tone.",
    defaultValue: 0,
    defaultMin: 0,
    defaultMax: 0,
  },
  {
    key: "invert",
    label: "Invert colors",
    group: "color",
    kind: "boolean",
    min: 0,
    max: 1,
    step: 1,
    description: "Produces a photographic-negative effect.",
    defaultValue: 0,
    defaultMin: 0,
    defaultMax: 0,
  },
  {
    key: "sharpen",
    label: "Sharpen / edge-enhance",
    group: "texture",
    kind: "range",
    min: 0,
    max: 10,
    step: 0.1,
    description: "Boosts edge and surface detail (good for engraved relief).",
    defaultValue: 0,
    defaultMin: 0.5,
    defaultMax: 2,
  },
  {
    key: "blur",
    label: "Gaussian blur",
    group: "texture",
    kind: "range",
    min: 0,
    max: 10,
    step: 0.1,
    description: "Softens focus, simulating motion or lens blur.",
    defaultValue: 0,
    defaultMin: 0,
    defaultMax: 1.5,
  },
  {
    key: "gaussianNoise",
    label: "Gaussian noise",
    group: "texture",
    kind: "range",
    min: 0,
    max: 50,
    step: 1,
    description: "Adds random sensor-like grain.",
    defaultValue: 0,
    defaultMin: 0,
    defaultMax: 12,
  },
  {
    key: "saltPepperNoise",
    label: "Salt & pepper noise",
    group: "texture",
    kind: "range",
    min: 0,
    max: 5,
    step: 0.1,
    unit: "%",
    description: "Randomly flips a fraction of pixels to black or white.",
    defaultValue: 0,
    defaultMin: 0,
    defaultMax: 1,
  },
  {
    key: "vignette",
    label: "Vignette",
    group: "creative",
    kind: "range",
    min: 0,
    max: 100,
    step: 1,
    unit: "%",
    description: "Darkens the edges, simulating macro-lens light fall-off.",
    defaultValue: 0,
    defaultMin: 20,
    defaultMax: 55,
  },
  {
    key: "glare",
    label: "Glare / highlight spot",
    group: "creative",
    kind: "range",
    min: 0,
    max: 100,
    step: 1,
    unit: "%",
    description: "Adds a soft bright reflection spot at a random position, simulating metallic glare.",
    defaultValue: 0,
    defaultMin: 15,
    defaultMax: 45,
  },
];

export const FILTER_MAP: Record<FilterKey, FilterMeta> = FILTER_REGISTRY.reduce(
  (acc, meta) => {
    acc[meta.key] = meta;
    return acc;
  },
  {} as Record<FilterKey, FilterMeta>
);

export function defaultFilterState(meta: FilterMeta, enabled = false): FilterState {
  return {
    enabled,
    value: meta.defaultValue,
    min: meta.defaultMin,
    max: meta.defaultMax,
    chance: meta.kind === "boolean" ? 50 : 100,
  };
}

export function clampFilterState(meta: FilterMeta, state: FilterState): FilterState {
  const clamp = (n: number) => Math.min(meta.max, Math.max(meta.min, n));
  return {
    enabled: !!state.enabled,
    value: meta.kind === "boolean" ? (state.value ? 1 : 0) : clamp(Number(state.value) || 0),
    min: meta.kind === "boolean" ? 0 : clamp(Number(state.min) || meta.min),
    max: meta.kind === "boolean" ? 1 : clamp(Number(state.max) || meta.max),
    chance: Math.min(100, Math.max(0, Number(state.chance) || 0)),
  };
}
